"""empty message

Revision ID: 6aac70c39249
Revises: fda2b1f3ace6
Create Date: 2018-05-29 23:52:25.836138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aac70c39249'
down_revision = 'fda2b1f3ace6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.String(length=64), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_payment')
    # ### end Alembic commands ###
