"""empty message

Revision ID: fda2b1f3ace6
Revises: 7b7d28352088
Create Date: 2018-05-26 15:57:03.098733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda2b1f3ace6'
down_revision = '7b7d28352088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('choosed_year', sa.Integer(), nullable=True),
    sa.Column('choosed_semester', sa.Integer(), nullable=True),
    sa.Column('rating', sa.JSON(), nullable=True),
    sa.Column('module', sa.JSON(), nullable=True),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rating')
    # ### end Alembic commands ###
